# Applied Machine Learning HomeWork 1
Due 09/29/21 11:59pm

## Task 1: Data Visualization and Analysis

You can download the FIFA 19 complete dataset from

https://www.kaggle.com/karangadiya/fifa19

Please replace the value of PATH_TO_DATASET variable in the following block with the path to your dataset

In [11]:
!conda uninstall matplotlib

^C


In [ ]:
!conda install matplotlib

In [4]:
# import modules, read data
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
# import seaborn as sns

## TODO: Replace with the path to your dataset
PATH_TO_DATASET = './archive/data.csv' 
############################################################

df = pd.read_csv(PATH_TO_DATASET)
df.head()

Unnamed: 0      ID               Name  Age  \
0           0  158023           L. Messi   31   
1           1   20801  Cristiano Ronaldo   33   
2           2  190871          Neymar Jr   26   
3           3  193080             De Gea   27   
4           4  192985       K. De Bruyne   27   

                                            Photo Nationality  \
0  https://cdn.sofifa.org/players/4/19/158023.png   Argentina   
1   https://cdn.sofifa.org/players/4/19/20801.png    Portugal   
2  https://cdn.sofifa.org/players/4/19/190871.png      Brazil   
3  https://cdn.sofifa.org/players/4/19/193080.png       Spain   
4  https://cdn.sofifa.org/players/4/19/192985.png     Belgium   

                                  Flag  Overall  Potential  \
0  https://cdn.sofifa.org/flags/52.png       94         94   
1  https://cdn.sofifa.org/flags/38.png       94         94   
2  https://cdn.sofifa.org/flags/54.png       92         93   
3  https://cdn.sofifa.org/flags/45.png       91         93   
4   https://cdn.sofifa.org/flags/7.png       91         92   

                  Club  ... Composure Marking StandingTackle  SlidingTackle  \
0         FC Barcelona  ...      96.0    33.0           28.0           26.0   
1             Juventus  ...      95.0    28.0           31.0           23.0   
2  Paris Saint-Germain  ...      94.0    27.0           24.0           33.0   
3    Manchester United  ...      68.0    15.0           21.0           13.0   
4      Manchester City  ...      88.0    68.0           58.0           51.0   

  GKDiving  GKHandling  GKKicking  GKPositioning GKReflexes Release Clause  
0      6.0        11.0       15.0           14.0        8.0        €226.5M  
1      7.0        11.0       15.0           14.0       11.0        €127.1M  
2      9.0         9.0       15.0           15.0       11.0        €228.1M  
3     90.0        85.0       87.0           88.0       94.0        €138.6M  
4     15.0        13.0        5.0           10.0       13.0        €196.4M  

[5 rows x 89 columns]

### 1.1 

Create a **scatter plot** of the Age vs Overall Rating. **Ensure the axes are labeled
properly.**

In [8]:
df['Overall']

0        94
1        94
2        92
3        91
4        91
         ..
18202    47
18203    47
18204    47
18205    47
18206    46
Name: Overall, Length: 18207, dtype: int64

In [9]:
x = np.random.normal(0, 1, 50)
x

array([-1.82747793, -0.93024736, -0.08692216,  0.41060434, -0.00691684,
        0.35529761, -1.49075896,  0.9118379 , -1.51776766,  0.22781015,
        0.42951315, -0.57421707, -0.44389789, -0.46303499, -0.904071  ,
        0.81604283,  1.16456877,  0.11335541,  0.19345615,  0.82427485,
        2.0303956 , -0.71918426, -0.73655348, -0.52737229,  2.47687523,
       -0.18732604, -0.5159757 ,  1.03326719, -0.41076354, -0.21036387,
        0.25007255,  1.93565321, -0.57673337,  0.26973229,  1.24541197,
        1.10289721,  0.80249409,  0.86244949, -0.79619042, -0.15597497,
       -0.22030223,  0.67083096, -0.96751011,  0.1730459 , -1.69900414,
        0.82643137, -1.25153706,  0.84809987, -0.55612164,  0.09398244])

In [10]:
plt.hist(x)

(array([ 4.,  2.,  8.,  9.,  9.,  4., 10.,  1.,  2.,  1.]),
 array([-1.82747793, -1.39704262, -0.9666073 , -0.53617199, -0.10573667,
         0.32469865,  0.75513396,  1.18556928,  1.6160046 ,  2.04643991,
         2.47687523]),
 <a list of 10 Patch objects>)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

In [5]:
# a = df.plot.scatter(x="Age", y="Overall")
sns.scatterplot(x="Age", y="Overall",data=df)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

### 1.2

Visualize the distribution of Overall Rating as a **histogram**. 

Do a small multiples plot of whether the player's prefered foot is left, i.e. do **one plot** of Overall Rating distribution for those players prefered left foot and **a separate** for those who prefer right foot (**within the same figure on separate axes**). **Ensure the axes are labeled properly and titles are added.**

In [ ]:
#YOUR CODE HERE

Can you spot differences in the distributions?

Answer:

### 1.3

Create a **pie chart** for distribution of Weak Foot for all the players. Get rid of players whose Weak Foot = nan. **Ensure each division is labeled properly and title is added**

In [ ]:
#YOUR CODE HERE

### 1.4 

Create **a boxplot and a violin plot** for distributions of players' ages in different positions (similar to plots on page 92 of Lecture 1 slide) Get rid of players whose position = nan. **Ensure the axes are labeled properly**

In [ ]:
# Your Code Here
# Create a boxplot

In [ ]:
# Your Code Here
# Create a violin plot

### 1.5
Creat a **stacked bar plot** for proportions of international reputation vs. players' ages (similar to the plot on page 97 of lecture 1 slide). **Ensure the axes and bars are labeled properly**

Note that international reputation takes value from [1,2,3,4,5]. Get rid of players whose international reputation is nan. 

Ages should be treated as intervals with width 5, i.e. the x-axis labels should be: 16 to 20, 21 to 25, 26 to 30,..., 41 to 45 

In [ ]:
# Your Code Here

## Task 2: Data Preprocessing and Supervised Learning

Use the dataset_credit.csv for this task. The target variable is 'class'.

### 2.1

Load the data and understand the data distributions - pick a few features and plot their distributions.


In [ ]:
# YOUR CODE HERE

### 2.2

**Preprocessing** - does any feature need pre-processing? Would you do any scaling to numerical features? Are there any categorical features? How would you handle the categorical features? Are there any features that has missing values? What % of values are missing in each of the features? Based on this percentages, would you consider dropping any features? How about adding a missing indicator? Would you consider adding a missing indicator column?

In [ ]:
# YOUR CODE HERE

### 2.3

**Data splitting** - Create development & test datasets.

In [ ]:
# YOUR CODE HERE

Give a reason on why did you use the particular splitting strategy.

Answer:

### 2.4

**Model selection** - Lets use k-nearest neighbors to train a model. Pick 2 out of 4 model selection strategies discussed in class to compare the optimal k chosen from both the methods. Also compare the results from grid search v.s. random search for finding the optimal k.

In [ ]:
# YOUR CODE HERE

### 2.5

Compare the performance of 4 models (2 model selection strategies & 2 hyperparameter search strategies) on the test set. Which combination performs the best? Any reasons why this combination gives the best performance?


In [ ]:
# YOUR CODE HERE